# Generated by Django 5.1.15 on 2026-03-18 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonconfirmation',
            name='confirmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonparticipant',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='academics.lesson'),
        ),
        migrations.AddField(
            model_name='lessonparticipant',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_participations', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='lessonconfirmation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='academics.lessonparticipant'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='lessonparticipant',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_participations', to='academics.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.studygroup'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.studygroup'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonconfirmation',
            unique_together={('participant', 'requested_from')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonparticipant',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('group', 'student')},
        ),
    ]
