# Generated by Django 5.1.15 on 2026-03-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='homework',
        ),
    ]
