# Generated by Django 5.1.15 on 2026-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_lesson_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
