# Generated by Django 5.1.15 on 2026-04-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studygroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title',
        ),
    ]

