# Generated by Django 5.1.15 on 2026-03-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcharge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='users.parentprofile'),
        ),
        migrations.AddField(
            model_name='parentcharge',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_charge', to='academics.lessonparticipant'),
        ),
        migrations.AddField(
            model_name='parentcharge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='teacherpayout',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payout', to='academics.lessonparticipant'),
        ),
        migrations.AddField(
            model_name='teacherpayout',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='users.teacherprofile'),
        ),
    ]
