# Generated by Django 5.1.15 on 2026-03-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telegram_chat_id_user_telegram_user_id_telegramlinktoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telegramlinktoken',
            new_name='users_teleg_token_59d219_idx',
            old_name='users_teleg_token_9d2b2b_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramlinktoken',
            new_name='users_teleg_expires_266f0c_idx',
            old_name='users_teleg_expires_4f1e2e_idx',
        ),
    ]
