# Generated by Django 5.1.15 on 2026-03-24

from django.db import migrations, models


def _prefix_at(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Canonicalize stored telegram_username to "@username".
    for user in User.objects.exclude(telegram_username__isnull=True).exclude(telegram_username=""):
        tu = (user.telegram_username or "").strip()
        if tu and not tu.startswith("@"):
            user.telegram_username = f"@{tu}"
            # Keep Django username aligned only if it was previously equal to telegram_username.
            if (user.username or "").strip() == tu:
                user.username = f"@{tu}"
                user.save(update_fields=["telegram_username", "username"])
            else:
                user.save(update_fields=["telegram_username"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_users_teleg_token_9d2b2b_idx_users_teleg_token_59d219_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=33, null=True, unique=True),
        ),
        migrations.RunPython(_prefix_at, migrations.RunPython.noop),
    ]

