# Generated by Django 5.1.15 on 2026-04-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_telegram_username_and_backfill_at_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparentrelation',
            name='relationship',
        ),
    ]
