# Generated by Django 5.1.15 on 2026-04-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studentparentrelation_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
    ]
